"""create drift_reports table

Revision ID: 8dd8a4bf1c14
Revises: df853853c22b
Create Date: 2026-07-07 16:08:31.295725

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8dd8a4bf1c14"
down_revision = "df853853c22b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drift_reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("dataset_id", sa.String(), nullable=True),
        sa.Column("reference_rows", sa.Integer(), nullable=True),
        sa.Column("target_rows", sa.Integer(), nullable=True),
        sa.Column("drift_detected", sa.Boolean(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drift_reports")
    # ### end Alembic commands ###
