"""add users table for JWT auth

Revision ID: c7574a60ef74
Revises: 0adaeec43e46
Create Date: 2026-07-24 12:55:57.029825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7574a60ef74'
down_revision = '0adaeec43e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_audit_log_table_created'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_customer_metadata_customer_id'), table_name='customer_metadata')
    op.drop_table('customer_metadata')
    op.drop_index(op.f('ix_exposures_customer_id'), table_name='exposures')
    op.drop_table('exposures')
    op.drop_index(op.f('ix_datasets_status'), table_name='datasets')
    op.drop_index(op.f('ix_training_jobs_dataset_id'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_finished_at'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_training_jobs_finished_at'), 'training_jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_training_jobs_dataset_id'), 'training_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_datasets_status'), 'datasets', ['status'], unique=False)
    op.create_table('exposures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('ab_group', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('ts', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exposures_pkey'))
    )
    op.create_index(op.f('ix_exposures_customer_id'), 'exposures', ['customer_id'], unique=False)
    op.create_table('customer_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_purchase_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_purchases', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_purchase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('churn_probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_metadata_pkey')),
    sa.UniqueConstraint('customer_id', name=op.f('customer_metadata_customer_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_customer_metadata_customer_id'), 'customer_metadata', ['customer_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('operation', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('changes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_table_created'), 'audit_log', ['table_name', 'created_at'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
